export function safeUrl(raw){try{const aliases={'wikipedia':'https://www.wikipedia.org/','википедия':'https://www.wikipedia.org/','википедию':'https://www.wikipedia.org/'};if(aliases[raw.toLowerCase()])return aliases[raw.toLowerCase()];const explicit=/^https?:\/\//i.test(raw);if(!explicit&&!/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}(?::\d+)?(?:[/?#].*)?$/i.test(raw))return null;const u=new URL(explicit?raw:'https://'+raw);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export function planLocal(command,items){const c=command.trim().toLowerCase();if(/^(назад|go back|back)$/.test(c))return {kind:'back'};if(/(прокрути|scroll)/.test(c))return {kind:'scroll',delta:/(вверх|up)/.test(c)?-520:520};const fill=command.match(/^(?:введи|напиши|type|fill)\s+(.+)$/i);if(fill){const item=items.find(x=>x.kind==='fill');return item?{kind:'fill',id:item.id,text:fill[1]}:{kind:'none',reason:'На странице нет доступного текстового поля'};}const navigationCommand=command.trim().replace(/^(?:(?:привет|пожалуйста)[,!\s]+)+/i,'').replace(/[.!?,]+$/,'');const open=navigationCommand.match(/^(?:открой|открою|open|go to|navigate to|перейди на)\s+(\S+)$/i);if(open){const url=safeUrl(open[1]);return url?{kind:'navigate',url}:{kind:'none',reason:'Укажите HTTP(S) адрес, домен или Википедию'};}const label=c.replace(/^(нажми|кликни|click)\s+/,'');const exact=items.filter(x=>x.kind==='click'&&x.label.toLowerCase()===label);const matches=exact.length?exact:items.filter(x=>x.kind==='click'&&x.label.toLowerCase().includes(label));const unique=new Set(matches.map(x=>x.label));return matches.length&&unique.size===1?{kind:'click',id:matches[0].id,confirm:matches[0].confirm}: {kind:'none',reason:matches.length?'Уточните название: найдено несколько элементов':'Подходящий элемент не найден'};}
export function validateJev(data,candidates,threshold=.65){
 const answer=data?.answers?.action,p=answer?.probabilities,decimals=data?.rounding?.probabilityDecimals;
 if(decimals!==undefined&&(!Number.isInteger(decimals)||decimals<0||decimals>15))throw Error('Некорректная точность вероятностей Jev');
 const roundingError=decimals===undefined?0:.5*10**-decimals;
 if(!answer||!Object.hasOwn(candidates,answer.choice)||!p||Object.keys(p).length!==Object.keys(candidates).length)throw Error('Некорректный ответ Jev');
 let sum=0;for(const id of Object.keys(candidates)){if(!Number.isFinite(p[id])||p[id]<0||p[id]>1)throw Error('Некорректные вероятности Jev');sum+=p[id];}
 if(Math.abs(sum-1)>.03+Object.keys(candidates).length*roundingError)throw Error('Сумма вероятностей Jev не равна 1');
 const sorted=Object.entries(p).sort((a,b)=>b[1]-a[1]);if(sorted[0][0]!==answer.choice)throw Error('Выбор Jev не совпадает с вероятностями');
 return {choice:p[answer.choice]-roundingError>=threshold&&sorted[0][1]-(sorted[1]?.[1]||0)-2*roundingError>=.1?answer.choice:'none',probabilities:p};
}
export class Epoch{value=0;next(){return ++this.value;}valid(value){return value===this.value;}}
