import test from 'node:test';import assert from 'node:assert/strict';import {planLocal,safeUrl,validateJev,Epoch}from '../core.js';
const items=[{id:'e0',label:'Документация',kind:'click'},{id:'e1',label:'Заметка',kind:'fill'}];
test('локальные команды выбирают конкретные DOM действия',()=>{assert.deepEqual(planLocal('нажми Документация',items),{kind:'click',id:'e0',confirm:undefined});assert.equal(planLocal('напиши Привет',items).text,'Привет');assert.equal(planLocal('назад',items).kind,'back');assert.equal(planLocal('прокрути вверх',items).delta,-520);assert.equal(planLocal('удали всё',items).kind,'none');});
test('опасные схемы запрещены',()=>{for(const url of ['javascript:alert(1)','file:///etc/passwd','data:text/html,test','chrome://settings'])assert.equal(safeUrl(url),null);assert.equal(safeUrl('wikipedia.org'),'https://wikipedia.org/');});
test('Jev probabilities проверены и низкая уверенность воздерживается',()=>{const c={e0:'click',none:'nothing'},data=p=>({answers:{action:{choice:'e0',probabilities:p}}});assert.equal(validateJev(data({e0:.9,none:.1}),c).choice,'e0');assert.equal(validateJev(data({e0:.55,none:.45}),c).choice,'none');assert.throws(()=>validateJev(data({e0:1.2,none:-.2}),c));assert.throws(()=>validateJev(data({e0:.9,unknown:.1}),c));assert.throws(()=>validateJev(data({e0:.4,none:.6}),c));});
test('новая команда или остановка инвалидирует старый запрос',()=>{const e=new Epoch(),first=e.next();assert(e.valid(first));e.next();assert(!e.valid(first));});
test('literal URL navigation aliases ограничены HTTP(S)',()=>{for(const prefix of ['go to','navigate to','перейди на','открой','open']){assert.deepEqual(planLocal(prefix+' wikipedia.com',[]),{kind:'navigate',url:'https://wikipedia.com/'});assert.equal(planLocal(prefix+' javascript:alert(1)',[]).kind,'none');assert.equal(planLocal(prefix+' chrome://settings',[]).kind,'none');}});
test('известное название сайта и ограниченные речевые вводные',()=>{for(const command of ['открой Википедию','привет открой Википедию','Привет, пожалуйста открою Википедию!','open Wikipedia'])assert.deepEqual(planLocal(command,[]),{kind:'navigate',url:'https://www.wikipedia.org/'});assert.equal(safeUrl('несуществующееназвание'),null);assert.equal(planLocal('открой неизвестно',[]).kind,'none');assert.equal(safeUrl('https://example.org/a'),'https://example.org/a');});
test('объявленное SDK округление учитывается без ослабления порога действия',()=>{const candidates={e0:'target',none:'nothing'},probabilities={e0:.7,none:0};for(let i=1;i<100;i++){candidates['e'+i]='small';probabilities['e'+i]=0;}const data={answers:{action:{choice:'e0',probabilities}},rounding:{probabilityDecimals:2}};assert.equal(validateJev(data,candidates).choice,'e0');assert.throws(()=>validateJev({...data,rounding:undefined},candidates));assert.throws(()=>validateJev({...data,rounding:{probabilityDecimals:-1}},candidates));const boundary={answers:{action:{choice:'e0',probabilities:{e0:.65,none:.35}}},rounding:{probabilityDecimals:2}};assert.equal(validateJev(boundary,{e0:'target',none:'nothing'}).choice,'none');assert.throws(()=>validateJev({...data,answers:{action:{choice:'e0',probabilities:{...probabilities,e0:1.5}}}},candidates));});
