import test from 'node:test';
import http from 'node:http';
import assert from 'node:assert/strict';
import {createServer} from '../server.mjs';
const payload={state:{user_command:'open Docs',compact_page_state:{title:'Public demo',elements:[{id:'e1',label:'Docs',kind:'link'}]}},questions:{action:{type:'choice',instructions:'Choose action',criteria:{e1:'click Docs',none:'Do nothing'}}}};
let nextPort=18765;
async function fixture(t,decide=async()=>({model:'typesafe-ai/jev',answers:{action:{type:'choice',choice:'e1',probabilities:{e1:1,none:0}}},usage:{inputTokens:5,outputTokens:0,totalTokens:5},decisionMs:1})){
 const port=nextPort++;const server=createServer({port,adapter:{configured:true,decide}});await new Promise(r=>server.listen(port,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base=`http://127.0.0.1:${port}`;const status=await(await fetch(base+'/api/status')).json();return {base,token:status.sessionToken};
}
const post=(f,body=payload,headers={})=>fetch(f.base+'/api/decide',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':f.token,...headers},body:JSON.stringify(body)});
test('native choice preserved; only public normalized response',async t=>{const f=await fixture(t);const r=await post(f);assert.equal(r.status,200);const data=await r.json();assert.equal(data.answers.action.choice,'e1');assert.deepEqual(data.usage,{inputTokens:5,outputTokens:0,totalTokens:5});assert.ok(!JSON.stringify(data).includes('sessionToken'));});
test('reject hostile Host, Origin, missing token and asset access',async t=>{const f=await fixture(t);assert.equal(await new Promise(resolve=>{http.get(f.base+'/api/status',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);});}),403);assert.equal((await fetch(f.base+'/api/status',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await post(f,payload,{'X-Session-Token':''})).status,403);assert.equal((await fetch(f.base+'/gateway.mjs')).status,404);});
test('pair requires local authenticated interaction',async t=>{const f=await fixture(t);const origin='chrome-extension://'+'a'.repeat(32);const pending=await(await fetch(f.base+'/api/status',{headers:{Origin:origin}})).json();assert.equal(pending.paired,false);assert.equal(pending.sessionToken,undefined);const noOrigin=await(await fetch(f.base+'/api/status',{headers:{'X-Extension-Id':'a'.repeat(32)}})).json();assert.equal(noOrigin.paired,false);assert.equal(noOrigin.sessionToken,undefined);assert.equal((await post(f,payload,{'X-Extension-Id':'a'.repeat(32)})).status,403);const r=await fetch(f.base+'/api/session',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':f.token,Origin:f.base},body:JSON.stringify({extensionId:'a'.repeat(32)})});assert.equal(r.status,200);const paired=await(await fetch(f.base+'/api/status',{headers:{'X-Extension-Id':'a'.repeat(32)}})).json();assert.equal(paired.paired,true);assert.equal(paired.sessionToken,f.token);assert.equal((await post(f,payload,{'X-Extension-Id':'a'.repeat(32),Origin:origin})).status,200);});
test('caps schema and body before model call; sanitizes errors',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;throw Error('PRIVATE_API_KEY internal private URL');});assert.equal((await post(f,{})).status,400);assert.equal((await post(f,{...payload,state:{text:'x'.repeat(70000)}})).status,413);const r=await post(f);assert.equal(r.status,502);assert.ok(!(await r.text()).includes('PRIVATE'));assert.equal(calls,1);});
test('browser cancellation aborts actual adapter and blocks concurrent calls',async t=>{let began,aborted;const started=new Promise(r=>began=r),cancelled=new Promise(r=>aborted=r);const f=await fixture(t,async(_,signal)=>{began();await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>{aborted();reject(Error('aborted'));},{once:true});});});const controller=new AbortController();const pending=fetch(f.base+'/api/decide',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':f.token},body:JSON.stringify(payload),signal:controller.signal}).catch(()=>{});await started;assert.equal((await post(f)).status,429);controller.abort();await pending;await cancelled;});
test('adapter forwards zero retries, cancellation; hides raw provider metadata',async()=>{const {createAdapter,normalizeResult,validateInput}=await import('../gateway.mjs');const signal=new AbortController().signal;let options;const a=await createAdapter({apiKey:'fake-secret-unit-key',evaluateFn:async o=>{options=o;return {answers:{action:{type:'choice',choice:'e1',probabilities:{e1:0.9,none:0.1}}},usage:{inputTokens:8,outputTokens:2,totalTokens:10},rounding:{probabilityDecimals:2,private:'secret'},response:{headers:{private:'secret'}},providerMetadata:{typesafe:{confidence:{action:0.8}},private:'secret'}};}});const r=await a.decide(payload,signal);assert.equal(options.maxRetries,0);assert.equal(options.abortSignal,signal);assert.equal(r.answers.action.confidence,0.8);assert.deepEqual(r.rounding,{probabilityDecimals:2});assert.ok(!JSON.stringify(r).includes('secret'));assert.throws(()=>normalizeResult({answers:{action:{type:'choice',choice:'unknown'}}},payload.questions,1));assert.throws(()=>validateInput({...payload,state:{...payload.state,compact_page_state:{elements:Array.from({length:252},(_,i)=>({id:'e'+i,label:'x',kind:'link'}))}}}));});
